export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  PART_CHECK_FAILED: "PART_CHECK_FAILED",
  CREW_TICKET_MISMATCH: "CREW_TICKET_MISMATCH",
  TICKET_ALREADY_RESTORED: "TICKET_ALREADY_RESTORED",
  ADJUST_NOTE_REQUIRED: "ADJUST_NOTE_REQUIRED"
} as const;
