export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  TICKET_NOT_FOUND: "TICKET_NOT_FOUND",
  TICKET_ALREADY_RESTORED: "TICKET_ALREADY_RESTORED",
  TICKET_NOT_RESTORED: "TICKET_NOT_RESTORED",
  CREW_TICKET_MISMATCH: "CREW_TICKET_MISMATCH",
  SPARE_PART_REJECTED: "SPARE_PART_REJECTED",
  SPARE_PART_QTY_MISMATCH: "SPARE_PART_QTY_MISMATCH",
  ADJUST_NOTE_REQUIRED: "ADJUST_NOTE_REQUIRED",
  USAGE_NOT_FOUND: "USAGE_NOT_FOUND"
} as const;
